services:
  server:
    image: harbor2.vantage6.ai/infrastructure/server:4.5.5
    ports:
      - "5050:5000"
    volumes:
      - ./config/config.yaml:/mnt/config.yaml
    command: "uwsgi --http :5000 --gevent 1000 --http-websockets
        --master --callable app --disable-logging
        --wsgi-file /vantage6/vantage6-server/vantage6/server/wsgi.py
        --pyargv /mnt/config.yaml"

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: test-password-here-change-me

  ui:
    image: harbor2.vantage6.ai/infrastructure/ui:4.5.5
    ports:
      - "8080:80"
    environment:
      SERVER_URL: http://localhost:5050
      API_PATH: /api
    depends_on:
      - server
